services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - USE_CUDA=true
      - gpus=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
    - open-webui_default

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
    - open-webui_default

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    restart: unless-stopped
    networks:
      - open-webui_default


  grafana:
    image: grafana/grafana-oss  # open source
    container_name: grafana
    restart: unless-stopped
    environment:
    - GF_SERVER_ROOT_URL=http://my.grafana.server/
    - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
    - '4000:3000'  # Change this line to map port 4000 on the host to port 3000 in the container
    volumes:
     - '/home/xpert/Desktop/open-webui/grafana_data:/var/lib/grafana'  # Bind mount
    networks:
    - open-webui_default

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'  # Expose Prometheus on port 9090
    volumes:
      - /home/xpert/Desktop/open-webui/prometheus.yml:/etc/prometheus/prometheus.yml  # Map prometheus.yml config file
      - /home/xpert/Desktop/open-webui/prometheus_data:/prometheus/data  # Ensure data directory is mapped correctly
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - ollama
    networks:
    - open-webui_default


  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'  # Needed to expose host-level metrics
    pid: host  # Allows access to host's PID namespace
    cap_add:
      - SYS_TIME  # Add SYS_TIME capability for accessing time-related syscalls
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'  # Mount host root filesystem as read-only for access to system metrics
    networks:
      - open-webui_default

  dcgm-exporter:
    image: nvidia/dcgm-exporter:latest
    container_name: dcgm-exporter
    runtime: nvidia  # Enable NVIDIA runtime for GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    cap_add:
      - SYS_ADMIN  # Add SYS_ADMIN capability
    ports:
      - "9400:9400"  # Expose DCGM Exporter on port 9400
    restart: unless-stopped
    networks:
      - open-webui_default


networks:
  open-webui_default:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}

